# ==============================================================================
#  CYD 2.8" HAMon - Home Assistant Monitor
#  A customisable clock & sensor dashboard for the ESP32 Cheap Yellow Display
#
#  Author: element-software
#  Date: 2026-02-13
#  License: MIT
#
#  Copyright (c) 2026 element-software
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#  THE SOFTWARE.
# ==============================================================================
#
#  SUBSTITUTIONS - Customise your dashboard by editing the values below.
#  Passwords and keys should be stored in your secrets.yaml file.
#
# ==============================================================================
substitutions:
  # --- Device ---
  device_name: "hamon" # Use the device name you entered when setting up a new ESPHome device
  friendly_name: "HAMon" # Can be whatever you like

  # --- Row 1, Column 1 ---
  r1c1_entity: "weather.pirateweather"
  r1c1_attribute: "humidity"
  r1c1_type: "sensor"
  r1c1_label: "Humidity"
  r1c1_icon: "\ue798"
  r1c1_icon_color: "0x00BFFF"
  r1c1_format: '%.0f%%'
  r1c1_color_thresh_high: "75"
  r1c1_color_thresh_mid: "60"
  r1c1_color_thresh_low: "40"

  # --- Row 1, Column 2 ---
  r1c2_entity: "binary_sensor.front_door_sensor_contact"
  r1c2_type: "binary"
  r1c2_label: "Front Door"
  r1c2_icon: "\ueffc"
  r1c2_icon_color: "0x888888"
  r1c2_state_on: "Open"
  r1c2_state_off: "Closed"
  r1c2_color_on: "0xFF5252"
  r1c2_color_off: "0x32CD32"
  r1c2_invert: "false"   # true = inverte lógica ON/OFF para este slot

  # --- Row 2, Column 1 ---
  r2c1_entity: "weather.pirateweather"
  r2c1_attribute: "temperature"
  r2c1_type: "sensor"
  r2c1_label: "Outside"
  r2c1_icon: "\ue1ff"
  r2c1_icon_color: "0x00BFFF"
  r2c1_format: '%.1f°C'
  r2c1_color_thresh_high: "30"
  r2c1_color_thresh_mid: "25"
  r2c1_color_thresh_low: "15"

  # --- Row 2, Column 2 ---
  r2c2_entity: "binary_sensor.gate_door_contact"
  r2c2_type: "binary"
  r2c2_label: "Gate"
  r2c2_icon: "\ue559"
  r2c2_icon_color: "0x888888"
  r2c2_state_on: "Open"
  r2c2_state_off: "Closed"
  r2c2_color_on: "0xFF5252"
  r2c2_color_off: "0x32CD32"
  r2c2_invert: "false"   # true = inverte lógica ON/OFF para este slot

  # --- Row 3, Column 1 ---
  r3c1_entity: "binary_sensor.garden_pano_person_occupancy"
  r3c1_type: "binary"
  r3c1_label: "Garden"
  r3c1_icon: "\ue7fd"
  r3c1_icon_color: "0x888888"
  r3c1_state_on: "Detected"
  r3c1_state_off: "Clear"
  r3c1_color_on: "0xFF5252"
  r3c1_color_off: "0x32CD32"
  r3c1_invert: "false"   # true = inverte lógica ON/OFF para este slot

  # --- Row 3, Column 2 ---
  r3c2_entity: "binary_sensor.loft_access_door_contact"
  r3c2_type: "binary"
  r3c2_label: "Loft"
  r3c2_icon: "\ue88a"
  r3c2_icon_color: "0x888888"
  r3c2_state_on: "Open"
  r3c2_state_off: "Closed"
  r3c2_color_on: "0xFF5252"
  r3c2_color_off: "0x32CD32"
  r3c2_invert: "false"   # true = inverte lógica ON/OFF para este slot

# ==============================================================================
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

# Replace with the API encryption key provided by your ESPHome instance
api:
  encryption:
    key: !secret api_key

# Replace with the OTA password provided by your ESPHome instance
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret ap_password

captive_portal:

output:
  - platform: ledc
    pin: GPIO21
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    id: backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 0.5s

spi:
  - id: tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

display:
  - platform: ili9xxx
    id: my_display
    model: ILI9341
    spi_id: tft
    cs_pin: GPIO15
    dc_pin: GPIO2
    auto_clear_enabled: false
    invert_colors: false
    color_order: RGB
    dimensions:
      width: 240
      height: 320
    transform:
      swap_xy: true
      mirror_y: true
      mirror_x: true

touchscreen:
  platform: xpt2046
  id: my_touchscreen
  spi_id: touch
  cs_pin: GPIO33
  calibration:
    x_min: 220
    x_max: 3756
    y_min: 394
    y_max: 3749
  transform:
    swap_xy: false
    mirror_x: true
    mirror_y: true

# --- FONTS ---
font:
  - file: "gfonts://Roboto"
    id: clock_font
    size: 48
    glyphs: '0123456789: '
  - file: "gfonts://Roboto"
    id: date_font
    size: 20
    glyphs: "0123456789/- abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
  - file: "gfonts://Material Icons"
    id: icon_font
    size: 28
    glyphs: "${r1c1_icon}${r1c2_icon}${r2c1_icon}${r2c2_icon}${r3c1_icon}${r3c2_icon}"
  - file: "gfonts://Roboto"
    id: state_font
    size: 18
    glyphs: '0123456789ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvwxyz .°%W-'
  - file: "gfonts://Roboto"
    id: label_font
    size: 11
    glyphs: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .°%-"

# --- TIME ---
time:
  - platform: homeassistant
    id: esptime
    on_time:
      - seconds: 0
        then:
          - lvgl.label.update:
              id: label_clock
              text: !lambda 'return id(esptime).now().strftime("%H:%M");'
          - lvgl.label.update:
              id: label_date
              text: !lambda |-
                static const char *const dias[] = {"Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"};
                auto now = id(esptime).now();
                return str_sprintf("%s %02d/%02d", dias[now.day_of_week - 1], now.day_of_month, now.month);

# --- DISPLAY PAGE CONFIG ---
lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  pages:
    - id: main_page
      bg_color: 0x000000
      widgets:
        - label:
            id: label_clock
            text: "--:--"
            text_font: clock_font
            text_color: 0xFFFFFF
            align: TOP_MID
            y: 5
        - label:
            id: label_date
            text: "--- --/--"
            text_font: date_font
            text_color: 0xAAAAAA
            align: TOP_MID
            y: 55

        # ====== ROW 1 ======
        - obj:
            x: 2
            y: 100
            width: 117
            height: 68
            bg_opa: TRANSP
            border_width: 0
            radius: 0
            widgets:
              - label:
                  id: icon_r1c1
                  text: "${r1c1_icon}"
                  text_font: icon_font
                  text_color: ${r1c1_icon_color}
                  align: LEFT_MID
                  x: 0
              - label:
                  text: "${r1c1_label}"
                  text_font: label_font
                  text_color: 0xAAAAAA
                  align: LEFT_MID
                  x: 32
                  y: -10
              - label:
                  id: val_r1c1
                  text: "--"
                  text_font: state_font
                  text_color: 0xFFFFFF
                  align: LEFT_MID
                  x: 32
                  y: 10

        - obj:
            x: 121
            y: 100
            width: 117
            height: 68
            bg_opa: TRANSP
            border_width: 0
            radius: 0
            widgets:
              - label:
                  id: icon_r1c2
                  text: "${r1c2_icon}"
                  text_font: icon_font
                  text_color: ${r1c2_icon_color}
                  align: LEFT_MID
                  x: 0
              - label:
                  text: "${r1c2_label}"
                  text_font: label_font
                  text_color: 0xAAAAAA
                  align: LEFT_MID
                  x: 32
                  y: -10
              - label:
                  id: val_r1c2
                  text: "--"
                  text_font: state_font
                  text_color: 0xFFFFFF
                  align: LEFT_MID
                  x: 32
                  y: 10

        # ====== ROW 2 ======
        - obj:
            x: 2
            y: 170
            width: 117
            height: 68
            bg_opa: TRANSP
            border_width: 0
            radius: 0
            widgets:
              - label:
                  id: icon_r2c1
                  text: "${r2c1_icon}"
                  text_font: icon_font
                  text_color: ${r2c1_icon_color}
                  align: LEFT_MID
                  x: 0
              - label:
                  text: "${r2c1_label}"
                  text_font: label_font
                  text_color: 0xAAAAAA
                  align: LEFT_MID
                  x: 32
                  y: -10
              - label:
                  id: val_r2c1
                  text: "--"
                  text_font: state_font
                  text_color: 0xFFFFFF
                  align: LEFT_MID
                  x: 32
                  y: 10

        - obj:
            x: 121
            y: 170
            width: 117
            height: 68
            bg_opa: TRANSP
            border_width: 0
            radius: 0
            widgets:
              - label:
                  id: icon_r2c2
                  text: "${r2c2_icon}"
                  text_font: icon_font
                  text_color: ${r2c2_icon_color}
                  align: LEFT_MID
                  x: 0
              - label:
                  text: "${r2c2_label}"
                  text_font: label_font
                  text_color: 0xAAAAAA
                  align: LEFT_MID
                  x: 32
                  y: -10
              - label:
                  id: val_r2c2
                  text: "--"
                  text_font: state_font
                  text_color: 0xFFFFFF
                  align: LEFT_MID
                  x: 32
                  y: 10

        # ====== ROW 3 ======
        - obj:
            x: 2
            y: 240
            width: 117
            height: 68
            bg_opa: TRANSP
            border_width: 0
            radius: 0
            widgets:
              - label:
                  id: icon_r3c1
                  text: "${r3c1_icon}"
                  text_font: icon_font
                  text_color: ${r3c1_icon_color}
                  align: LEFT_MID
                  x: 0
              - label:
                  text: "${r3c1_label}"
                  text_font: label_font
                  text_color: 0xAAAAAA
                  align: LEFT_MID
                  x: 32
                  y: -10
              - label:
                  id: val_r3c1
                  text: "--"
                  text_font: state_font
                  text_color: 0xFFFFFF
                  align: LEFT_MID
                  x: 32
                  y: 10

        - obj:
            x: 121
            y: 240
            width: 117
            height: 68
            bg_opa: TRANSP
            border_width: 0
            radius: 0
            widgets:
              - label:
                  id: icon_r3c2
                  text: "${r3c2_icon}"
                  text_font: icon_font
                  text_color: ${r3c2_icon_color}
                  align: LEFT_MID
                  x: 0
              - label:
                  text: "${r3c2_label}"
                  text_font: label_font
                  text_color: 0xAAAAAA
                  align: LEFT_MID
                  x: 32
                  y: -10
              - label:
                  id: val_r3c2
                  text: "--"
                  text_font: state_font
                  text_color: 0xFFFFFF
                  align: LEFT_MID
                  x: 32
                  y: 10

# --- BINARY SENSOR CONFIG ---
binary_sensor:
  - platform: homeassistant
    id: ha_r1c2
    entity_id: ${r1c2_entity}
    publish_initial_state: true
    on_state:
      then:
        - lvgl.label.update:
            id: icon_r1c2
            text_color: !lambda |-
              const bool inverted = std::string("${r1c2_invert}") == "true";
              const bool active = inverted ? !id(ha_r1c2).state : id(ha_r1c2).state;
              if (active) return lv_color_hex(${r1c2_color_on});
              return lv_color_hex(${r1c2_color_off});
        - lvgl.label.update:
            id: val_r1c2
            text: !lambda |-
              const bool inverted = std::string("${r1c2_invert}") == "true";
              const bool active = inverted ? !id(ha_r1c2).state : id(ha_r1c2).state;
              if (active) return "${r1c2_state_on}";
              return "${r1c2_state_off}";
            text_color: !lambda |-
              const bool inverted = std::string("${r1c2_invert}") == "true";
              const bool active = inverted ? !id(ha_r1c2).state : id(ha_r1c2).state;
              if (active) return lv_color_hex(${r1c2_color_on});
              return lv_color_hex(${r1c2_color_off});

  - platform: homeassistant
    id: ha_r2c2
    entity_id: ${r2c2_entity}
    publish_initial_state: true
    on_state:
      then:
        - lvgl.label.update:
            id: icon_r2c2
            text_color: !lambda |-
              const bool inverted = std::string("${r2c2_invert}") == "true";
              const bool active = inverted ? !id(ha_r2c2).state : id(ha_r2c2).state;
              if (active) return lv_color_hex(${r2c2_color_on});
              return lv_color_hex(${r2c2_color_off});
        - lvgl.label.update:
            id: val_r2c2
            text: !lambda |-
              const bool inverted = std::string("${r2c2_invert}") == "true";
              const bool active = inverted ? !id(ha_r2c2).state : id(ha_r2c2).state;
              if (active) return "${r2c2_state_on}";
              return "${r2c2_state_off}";
            text_color: !lambda |-
              const bool inverted = std::string("${r2c2_invert}") == "true";
              const bool active = inverted ? !id(ha_r2c2).state : id(ha_r2c2).state;
              if (active) return lv_color_hex(${r2c2_color_on});
              return lv_color_hex(${r2c2_color_off});

  - platform: homeassistant
    id: ha_r3c1
    entity_id: ${r3c1_entity}
    publish_initial_state: true
    on_state:
      then:
        - lvgl.label.update:
            id: icon_r3c1
            text_color: !lambda |-
              const bool inverted = std::string("${r3c1_invert}") == "true";
              const bool active = inverted ? !id(ha_r3c1).state : id(ha_r3c1).state;
              if (active) return lv_color_hex(${r3c1_color_on});
              return lv_color_hex(${r3c1_color_off});
        - lvgl.label.update:
            id: val_r3c1
            text: !lambda |-
              const bool inverted = std::string("${r3c1_invert}") == "true";
              const bool active = inverted ? !id(ha_r3c1).state : id(ha_r3c1).state;
              if (active) return "${r3c1_state_on}";
              return "${r3c1_state_off}";
            text_color: !lambda |-
              const bool inverted = std::string("${r3c1_invert}") == "true";
              const bool active = inverted ? !id(ha_r3c1).state : id(ha_r3c1).state;
              if (active) return lv_color_hex(${r3c1_color_on});
              return lv_color_hex(${r3c1_color_off});

  - platform: homeassistant
    id: ha_r3c2
    entity_id: ${r3c2_entity}
    publish_initial_state: true
    on_state:
      then:
        - lvgl.label.update:
            id: icon_r3c2
            text_color: !lambda |-
              const bool inverted = std::string("${r3c2_invert}") == "true";
              const bool active = inverted ? !id(ha_r3c2).state : id(ha_r3c2).state;
              if (active) return lv_color_hex(${r3c2_color_on});
              return lv_color_hex(${r3c2_color_off});
        - lvgl.label.update:
            id: val_r3c2
            text: !lambda |-
              const bool inverted = std::string("${r3c2_invert}") == "true";
              const bool active = inverted ? !id(ha_r3c2).state : id(ha_r3c2).state;
              if (active) return "${r3c2_state_on}";
              return "${r3c2_state_off}";
            text_color: !lambda |-
              const bool inverted = std::string("${r3c2_invert}") == "true";
              const bool active = inverted ? !id(ha_r3c2).state : id(ha_r3c2).state;
              if (active) return lv_color_hex(${r3c2_color_on});
              return lv_color_hex(${r3c2_color_off});

# --- NUMERIC SENSOR CONFIG ---
sensor:
  - platform: homeassistant
    id: ha_r1c1
    entity_id: ${r1c1_entity}
    attribute: ${r1c1_attribute}
    on_value:
      then:
        - lvgl.label.update:
            id: val_r1c1
            text: !lambda |-
              return str_sprintf("${r1c1_format}", x);
        - lvgl.label.update:
            id: icon_r1c1
            text_color: !lambda |-
              if (x > ${r1c1_color_thresh_high}) return lv_color_hex(0xFF0000);
              if (x > ${r1c1_color_thresh_mid}) return lv_color_hex(0xFF5252);
              if (x > ${r1c1_color_thresh_low}) return lv_color_hex(0xFFA500);
              return lv_color_hex(0x32CD32);

  - platform: homeassistant
    id: ha_r2c1
    entity_id: ${r2c1_entity}
    attribute: ${r2c1_attribute}
    on_value:
      then:
        - lvgl.label.update:
            id: val_r2c1
            text: !lambda |-
              return str_sprintf("${r2c1_format}", x);
        - lvgl.label.update:
            id: icon_r2c1
            text_color: !lambda |-
              if (x > ${r2c1_color_thresh_high}) return lv_color_hex(0xFF5252);
              if (x > ${r2c1_color_thresh_mid}) return lv_color_hex(0xFFA500);
              if (x < ${r2c1_color_thresh_low}) return lv_color_hex(0x00BFFF);
              return lv_color_hex(0x32CD32);
